### PR TITLE
Swift target

### PR DESCRIPTION
**Pull request by jeffreyguenther**
I've sync'd with @parrt's changes from today and have started to make the changes noted by @janyou.

### CODE REVIEW

**Comment by jeffreyguenther** [comment]
Closing because you've done some of this work yourself. :)

**Comment by ewanmellor** [comment]
@jeffreyguenther My rebase is done.  If you want to work on any of the test failures or the open issues that I filed today, go right ahead.  Please let me know what you're working on, because I hope to get some more time tomorrow and I don't want to stand on your toes.

I am currently seeing a bunch of Go-related test failures, which I presume Terrence will fix soon enough, and 9 Swift failures.  I guess that at least one of those is https://github.com/antlr/antlr4/issues/1332 but I don't know about all of them and I'd have to dig into them to understand.  If you know what's going on there, then that would be great.

**Comment by parrt** [comment]
@ewanmellor all tests appear to pass in the antlr/antlr4 master now. which tests fail for go?

**Comment by janyou** [comment]
@ewanmellor `.travis.yml` does not seem to configure the Swift runtime environment.

Travis CI job log:

> Cannot run program "xcrun" (in directory "/tmp/Antlr4"): error=2, No such file or directory

**Comment by ewanmellor** [comment]
@parrt It was a misleading error message.  It says "Missing system property:antlr-go" when what it means is "I can't find your Go installation".

```
java.lang.RuntimeException: Missing system property:antlr-go
        at org.antlr.v4.test.runtime.go.BaseTest.locateGo(BaseTest.java:519)
        at org.antlr.v4.test.runtime.go.BaseTest.cacheGoRuntime(BaseTest.java:173)
        at org.antlr.v4.test.runtime.go.BaseTest.setupGoRuntime(BaseTest.java:164)
```

**Comment by parrt** [comment]
@ewanmellor did you get it working then?

**Comment by jeffreyguenther** [comment]
@ewanmellor Thanks for the heads up! I'll post in https://github.com/antlr/antlr4/issues/945 if I'm going to tackle an issue. Proceed unless you hear otherwise from me 😄

**Comment by ewanmellor** [comment]
@parrt Yes.  Go 1.6 is broken on macOS Sierra, I had to upgrade go.  Go tests are passing for me now (just 9 Swift failures left to work through).

**Pull request closed without merging**
